# Use the official node image as base
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /frontend

# Copy package.json and package-lock.json to the container
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./frontend .

# Expose the port the app will run on and the debug port
EXPOSE 3000 9229 9230

# Start the Next.js app in debug mode
CMD ["npm", "run", "debug"]
