FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy everything
COPY ./backend ./

WORKDIR /app/Api
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 As runtime
WORKDIR /app
COPY --from=build-env /app/Api/out ./

ENV ASPNETCORE_URLS "http://+:5020"
EXPOSE 5020

ENTRYPOINT ["dotnet", "Api.dll"]
