version: '3.9'

services:
  budget-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: budget-backend
    restart: unless-stopped
    ports:
      - 5020:5020
    environment:
      - 'VIRTUAL_HOST=${HOST}'
      - 'VIRTUAL_PATH=/api'
      - 'VIRTUAL_NETWORK=${PROXY_HOST}'
      - 'VIRTUAL_PORT=5020'
      - 'ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}'
      - 'CONNECTION_STRING=${CONNECTION_STRING}'
      - 'ADMIN_USER=${ADMIN_USER:-""}'
      - 'ADMIN_PASSWORD=${ADMIN_PASSWORD:-""}'
    networks:
      - proxy-net

  budget-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: budget-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
    environment:
      - 'VIRTUAL_HOST=${HOST}'
      - 'VIRTUAL_PATH=/'
      - 'VIRTUAL_NETWORK=${PROXY_HOST}'
      - 'VIRTUAL_PORT=3000'
      - 'LETSENCRYPT_HOST=${HOST}'
      - 'LETSENCRYPT_EMAIL=${LE_EMAIL}'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - proxy-net

networks:
  proxy-net:
    name: home-server_proxy-tier
    external: true
