/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'income-categories': IncomeCategory;
    'expense-categories': ExpenseCategory;
    payees: Payee;
    accounts: Account;
    'recurring-items': RecurringItem;
    budgets: Budget;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'income-categories': IncomeCategoriesSelect<false> | IncomeCategoriesSelect<true>;
    'expense-categories': ExpenseCategoriesSelect<false> | ExpenseCategoriesSelect<true>;
    payees: PayeesSelect<false> | PayeesSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    'recurring-items': RecurringItemsSelect<false> | RecurringItemsSelect<true>;
    budgets: BudgetsSelect<false> | BudgetsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * The default account to show on your dashboard
   */
  defaultAccount?: (string | null) | Account;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * 📋 Step 2: Add your bank accounts (checking, savings, credit cards)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  name: string;
  description?: string | null;
  accountType: 'checking' | 'savings' | 'credit_card' | 'cash' | 'investment' | 'other';
  /**
   * The initial balance of this account
   */
  startingBalance: number;
  /**
   * The current balance (updated automatically by transactions)
   */
  currentBalance: number;
  hasInterestRate?: boolean | null;
  /**
   * Annual interest rate (e.g., 5.5 for 5.5%)
   */
  interestRate?: number | null;
  /**
   * How often this occurs
   */
  scheduleType:
    | 'weekly'
    | 'biweekly'
    | 'monthly'
    | 'bimonthly_1_15'
    | 'bimonthly_15_last'
    | 'quarterly'
    | 'semiannually'
    | 'annually';
  /**
   * Which day of the week does this occur?
   */
  dayOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6') | null;
  /**
   * When did/will this bi-weekly cycle start? (e.g., your first paycheck date)
   */
  anchorDate?: string | null;
  /**
   * Which day of the month does this occur?
   */
  dayOfMonth?:
    | (
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '25'
        | '26'
        | '27'
        | '28'
        | '29'
        | '30'
        | 'last'
      )
    | null;
  /**
   * Which month does this occur?
   */
  month?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * ✅ Auto-seeded • Income categories (edit or add more as needed)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "income-categories".
 */
export interface IncomeCategory {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ✅ Auto-seeded • Expense categories (edit or add more as needed)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories".
 */
export interface ExpenseCategory {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📋 Step 1: Add payees (employers, landlords, stores, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payees".
 */
export interface Payee {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📋 Step 3: Define your recurring income, expenses, and transfers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-items".
 */
export interface RecurringItem {
  id: string;
  category?: string | null;
  /**
   * What type of recurring item is this?
   */
  itemType: 'income' | 'expense' | 'transfer';
  name: string;
  amount: number;
  /**
   * Income category
   */
  incomeCategory?: (string | null) | IncomeCategory;
  /**
   * Expense category
   */
  expenseCategory?: (string | null) | ExpenseCategory;
  /**
   * Who you pay (expense) or who pays you (income)
   */
  payee?: (string | null) | Payee;
  /**
   * Account this income is deposited to or expense is paid from
   */
  account?: (string | null) | Account;
  /**
   * Account to transfer from
   */
  fromAccount?: (string | null) | Account;
  /**
   * Account to transfer to
   */
  toAccount?: (string | null) | Account;
  /**
   * Does this expense have a balance to track (e.g., credit card, loan)?
   */
  hasBalance?: boolean | null;
  balance?: {
    currentBalance?: number | null;
    /**
     * Annual interest rate (e.g., 18.5 for 18.5%)
     */
    interestRate?: number | null;
  };
  /**
   * How often this occurs
   */
  scheduleType:
    | 'weekly'
    | 'biweekly'
    | 'monthly'
    | 'bimonthly_1_15'
    | 'bimonthly_15_last'
    | 'quarterly'
    | 'semiannually'
    | 'annually';
  /**
   * Which day of the week does this occur?
   */
  dayOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6') | null;
  /**
   * When did/will this bi-weekly cycle start? (e.g., your first paycheck date)
   */
  anchorDate?: string | null;
  /**
   * Which day of the month does this occur?
   */
  dayOfMonth?:
    | (
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '25'
        | '26'
        | '27'
        | '28'
        | '29'
        | '30'
        | 'last'
      )
    | null;
  /**
   * Which month does this occur?
   */
  month?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  /**
   * Inactive items will not be included in new budget periods
   */
  isActive?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📅 Step 4: Create budget periods - containers for a slice of time (e.g., paycheck to paycheck)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budgets".
 */
export interface Budget {
  id: string;
  /**
   * E.g., "December 15th Paycheck" or "Budget 2024-01-15"
   */
  name: string;
  /**
   * The account this budget period manages
   */
  account: string | Account;
  /**
   * Start of this budget period
   */
  startDate: string;
  /**
   * End of this budget period
   */
  endDate: string;
  /**
   * Planning = setting up, Active = current period, Closed = completed/archived
   */
  status: 'planning' | 'active' | 'closed';
  /**
   * Notes about this budget period (goals, special circumstances, etc.)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Historical record of all financial transactions (optional)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  date: string;
  type: 'income' | 'expense' | 'transfer';
  description: string;
  amount: number;
  /**
   * Which budget this transaction belongs to
   */
  budget: string | Budget;
  incomeDetails?: {
    category?: (string | null) | IncomeCategory;
    payee?: (string | null) | Payee;
    account?: (string | null) | Account;
  };
  expenseDetails?: {
    category?: (string | null) | ExpenseCategory;
    payee?: (string | null) | Payee;
    account?: (string | null) | Account;
  };
  transferDetails?: {
    fromAccount?: (string | null) | Account;
    toAccount?: (string | null) | Account;
  };
  notes?: string | null;
  /**
   * Has this transaction been reconciled with your bank statement?
   */
  reconciled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'income-categories';
        value: string | IncomeCategory;
      } | null)
    | ({
        relationTo: 'expense-categories';
        value: string | ExpenseCategory;
      } | null)
    | ({
        relationTo: 'payees';
        value: string | Payee;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'recurring-items';
        value: string | RecurringItem;
      } | null)
    | ({
        relationTo: 'budgets';
        value: string | Budget;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  defaultAccount?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "income-categories_select".
 */
export interface IncomeCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories_select".
 */
export interface ExpenseCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payees_select".
 */
export interface PayeesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  accountType?: T;
  startingBalance?: T;
  currentBalance?: T;
  hasInterestRate?: T;
  interestRate?: T;
  scheduleType?: T;
  dayOfWeek?: T;
  anchorDate?: T;
  dayOfMonth?: T;
  month?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-items_select".
 */
export interface RecurringItemsSelect<T extends boolean = true> {
  category?: T;
  itemType?: T;
  name?: T;
  amount?: T;
  incomeCategory?: T;
  expenseCategory?: T;
  payee?: T;
  account?: T;
  fromAccount?: T;
  toAccount?: T;
  hasBalance?: T;
  balance?:
    | T
    | {
        currentBalance?: T;
        interestRate?: T;
      };
  scheduleType?: T;
  dayOfWeek?: T;
  anchorDate?: T;
  dayOfMonth?: T;
  month?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budgets_select".
 */
export interface BudgetsSelect<T extends boolean = true> {
  name?: T;
  account?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  date?: T;
  type?: T;
  description?: T;
  amount?: T;
  budget?: T;
  incomeDetails?:
    | T
    | {
        category?: T;
        payee?: T;
        account?: T;
      };
  expenseDetails?:
    | T
    | {
        category?: T;
        payee?: T;
        account?: T;
      };
  transferDetails?:
    | T
    | {
        fromAccount?: T;
        toAccount?: T;
      };
  notes?: T;
  reconciled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}