/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'income-categories': IncomeCategory;
    'expense-categories': ExpenseCategory;
    payees: Payee;
    accounts: Account;
    transactions: Transaction;
    'recurring-items': RecurringItem;
    budgets: Budget;
    'budget-items': BudgetItem;
    'budget-schedules': BudgetSchedule;
    'match-rules': MatchRule;
    'app-settings': AppSetting;
    'teller-insights': TellerInsight;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'income-categories': IncomeCategoriesSelect<false> | IncomeCategoriesSelect<true>;
    'expense-categories': ExpenseCategoriesSelect<false> | ExpenseCategoriesSelect<true>;
    payees: PayeesSelect<false> | PayeesSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'recurring-items': RecurringItemsSelect<false> | RecurringItemsSelect<true>;
    budgets: BudgetsSelect<false> | BudgetsSelect<true>;
    'budget-items': BudgetItemsSelect<false> | BudgetItemsSelect<true>;
    'budget-schedules': BudgetSchedulesSelect<false> | BudgetSchedulesSelect<true>;
    'match-rules': MatchRulesSelect<false> | MatchRulesSelect<true>;
    'app-settings': AppSettingsSelect<false> | AppSettingsSelect<true>;
    'teller-insights': TellerInsightsSelect<false> | TellerInsightsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * ✅ Auto-seeded • Income categories (edit or add more as needed)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "income-categories".
 */
export interface IncomeCategory {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ✅ Auto-seeded • Expense categories (edit or add more as needed)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories".
 */
export interface ExpenseCategory {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People and companies you transact with
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payees".
 */
export interface Payee {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bank accounts, credit cards, and cash accounts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  name: string;
  /**
   * Manual accounts are managed entirely in this app. Connected accounts sync transactions from your bank via Teller.
   */
  accountSource: 'manual' | 'teller';
  /**
   * Show this account by default on the frontend dashboard
   */
  isDefault?: boolean | null;
  description?: string | null;
  accountType: 'checking' | 'savings' | 'credit_card' | 'cash' | 'investment' | 'other';
  /**
   * The initial balance of this account
   */
  startingBalance: number;
  /**
   * The current balance (updated automatically by transactions)
   */
  currentBalance: number;
  hasInterestRate?: boolean | null;
  /**
   * Annual interest rate (e.g., 5.5 for 5.5%)
   */
  interestRate?: number | null;
  /**
   * How often this occurs
   */
  scheduleType:
    | 'weekly'
    | 'biweekly'
    | 'monthly'
    | 'bimonthly_1_15'
    | 'bimonthly_15_last'
    | 'quarterly'
    | 'semiannually'
    | 'annually';
  /**
   * Which day of the week does this occur?
   */
  dayOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6') | null;
  /**
   * When did/will this bi-weekly cycle start? (e.g., your first paycheck date)
   */
  anchorDate?: string | null;
  /**
   * Which day of the month does this occur?
   */
  dayOfMonth?:
    | (
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '25'
        | '26'
        | '27'
        | '28'
        | '29'
        | '30'
        | 'last'
      )
    | null;
  /**
   * Which month does this occur?
   */
  month?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  /**
   * Teller account ID (set automatically during Teller Connect)
   */
  tellerAccountId?: string | null;
  /**
   * Teller enrollment ID (set automatically)
   */
  tellerEnrollmentId?: string | null;
  /**
   * Bank/institution name from Teller
   */
  tellerInstitutionName?: string | null;
  /**
   * Teller access token (set during Teller Connect)
   */
  tellerAccessToken?: string | null;
  /**
   * When transactions were last pulled from Teller
   */
  tellerLastSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Record of all financial transactions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  date: string;
  /**
   * Which account this transaction affects
   */
  account: string | Account;
  type: 'income' | 'expense' | 'transfer';
  description: string;
  /**
   * Human-readable name shown in lists (e.g. "Sam's Club"). Auto-populated from payee or AI suggestion.
   */
  displayTitle?: string | null;
  /**
   * The merchant or person this transaction is with
   */
  payee?: (string | null) | Payee;
  amount: number;
  incomeDetails?: {
    category?: (string | null) | IncomeCategory;
    payee?: (string | null) | Payee;
  };
  expenseDetails?: {
    category?: (string | null) | ExpenseCategory;
    payee?: (string | null) | Payee;
  };
  transferDetails?: {
    /**
     * The account receiving the transfer
     */
    toAccount?: (string | null) | Account;
  };
  notes?: string | null;
  /**
   * Has this transaction been reconciled with your bank statement?
   */
  reconciled?: boolean | null;
  /**
   * Unique ID from Teller (used to prevent duplicate imports)
   */
  tellerTransactionId?: string | null;
  syncSource?: ('manual' | 'teller') | null;
  /**
   * How this transaction was categorized/matched
   */
  matchConfidence?: ('manual' | 'auto_rule' | 'auto_ai' | 'unmatched') | null;
  /**
   * The recurring item this transaction was matched to (set during sync)
   */
  matchedRecurringItem?: (string | null) | RecurringItem;
  updatedAt: string;
  createdAt: string;
}
/**
 * Recurring income, expenses, and transfers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-items".
 */
export interface RecurringItem {
  id: string;
  category?: string | null;
  /**
   * What type of recurring item is this?
   */
  itemType: 'income' | 'expense' | 'transfer';
  name: string;
  amount: number;
  /**
   * Income category
   */
  incomeCategory?: (string | null) | IncomeCategory;
  /**
   * Expense category
   */
  expenseCategory?: (string | null) | ExpenseCategory;
  /**
   * Who you pay (expense) or who pays you (income)
   */
  payee?: (string | null) | Payee;
  /**
   * Account this income is deposited to or expense is paid from
   */
  account?: (string | null) | Account;
  /**
   * Account to transfer from
   */
  fromAccount?: (string | null) | Account;
  /**
   * Account to transfer to
   */
  toAccount?: (string | null) | Account;
  /**
   * Does this expense have a balance to track (e.g., credit card, loan)?
   */
  hasBalance?: boolean | null;
  balance?: {
    currentBalance?: number | null;
    /**
     * Annual interest rate (e.g., 18.5 for 18.5%)
     */
    interestRate?: number | null;
  };
  /**
   * How often this occurs
   */
  scheduleType:
    | 'weekly'
    | 'biweekly'
    | 'monthly'
    | 'bimonthly_1_15'
    | 'bimonthly_15_last'
    | 'quarterly'
    | 'semiannually'
    | 'annually';
  /**
   * Which day of the week does this occur?
   */
  dayOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6') | null;
  /**
   * When did/will this bi-weekly cycle start? (e.g., your first paycheck date)
   */
  anchorDate?: string | null;
  /**
   * Which day of the month does this occur?
   */
  dayOfMonth?:
    | (
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '25'
        | '26'
        | '27'
        | '28'
        | '29'
        | '30'
        | 'last'
      )
    | null;
  /**
   * Which month does this occur?
   */
  month?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  /**
   * Inactive items will not be included in new budget periods
   */
  isActive?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Time-based budget periods (paycheck to paycheck)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budgets".
 */
export interface Budget {
  id: string;
  /**
   * E.g., "December 15th Paycheck" or "Budget 2024-01-15"
   */
  name: string;
  /**
   * The account this budget period manages
   */
  account: string | Account;
  /**
   * Start of this budget period
   */
  startDate: string;
  /**
   * End of this budget period
   */
  endDate: string;
  /**
   * Planning = setting up, Active = current period, Closed = completed/archived
   */
  status: 'planning' | 'active' | 'closed';
  /**
   * Notes about this budget period (goals, special circumstances, etc.)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks recurring items within budget periods and their actualization status
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget-items".
 */
export interface BudgetItem {
  id: string;
  /**
   * The budget period this item belongs to
   */
  budget: string | Budget;
  /**
   * The recurring item this budget item is based on
   */
  recurringItem: string | RecurringItem;
  /**
   * When this item is due/expected within the budget period
   */
  dueDate: string;
  /**
   * Has this budget item been recorded as a transaction?
   */
  isActualized?: boolean | null;
  /**
   * The transaction that actualized this budget item
   */
  transaction?: (string | null) | Transaction;
  /**
   * Optional notes about this budget item
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Automated budget period creation and management
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget-schedules".
 */
export interface BudgetSchedule {
  id: string;
  /**
   * A name for this budget schedule
   */
  name: string;
  /**
   * Which account to create budgets for
   */
  account: string | Account;
  /**
   * How often to create new budget periods
   */
  scheduleType:
    | 'weekly'
    | 'biweekly'
    | 'monthly'
    | 'bimonthly_1_15'
    | 'bimonthly_15_last'
    | 'quarterly'
    | 'semiannually'
    | 'annually';
  /**
   * Which day of the week does this occur?
   */
  dayOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6') | null;
  /**
   * When did/will this bi-weekly cycle start? (e.g., your first paycheck date)
   */
  anchorDate?: string | null;
  /**
   * Which day of the month does this occur?
   */
  dayOfMonth?:
    | (
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '25'
        | '26'
        | '27'
        | '28'
        | '29'
        | '30'
        | 'last'
      )
    | null;
  /**
   * Which month does this occur?
   */
  month?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  /**
   * Template for budget names. Use {start} and {end} for dates.
   */
  budgetNamePattern?: string | null;
  /**
   * Enable automatic budget creation for this schedule
   */
  isActive?: boolean | null;
  /**
   * How many future "planned" budgets to maintain
   */
  lookAhead?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-categorization and recurring item matching rules for synced transactions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-rules".
 */
export interface MatchRule {
  id: string;
  /**
   * Human-readable label, e.g. "Netflix subscription"
   */
  name: string;
  /**
   * Substring or /regex/ to match against the raw transaction description (case-insensitive)
   */
  descriptionPattern: string;
  /**
   * Optionally restrict to a specific transaction type
   */
  transactionType?: ('any' | 'income' | 'expense' | 'transfer') | null;
  /**
   * Minimum amount (inclusive). Leave blank for no lower bound.
   */
  amountMin?: number | null;
  /**
   * Maximum amount (inclusive). Leave blank for no upper bound.
   */
  amountMax?: number | null;
  /**
   * When this rule matches, link the transaction to this recurring item and auto-record its budget item
   */
  recurringItem?: (string | null) | RecurringItem;
  /**
   * Payee to assign to matching transactions
   */
  payee?: (string | null) | Payee;
  /**
   * Expense category to assign when this rule matches
   */
  expenseCategory?: (string | null) | ExpenseCategory;
  /**
   * Income category to assign when this rule matches
   */
  incomeCategory?: (string | null) | IncomeCategory;
  /**
   * Higher number = evaluated first. Useful when multiple rules could match.
   */
  priority?: number | null;
  /**
   * Disabled rules are ignored during matching
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings".
 */
export interface AppSetting {
  id: string;
  /**
   * Marks whether the initial setup wizard has been completed.
   */
  wizardComplete?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-generated categorization suggestions for synced transactions, pending review
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teller-insights".
 */
export interface TellerInsight {
  id: string;
  /**
   * Normalized description key used for deduplication (auto-generated)
   */
  descriptionKey: string;
  /**
   * Exact description text from the bank (for display and rule creation)
   */
  exampleDescription: string;
  transactionType: 'expense' | 'income' | 'transfer';
  /**
   * Amount from the transaction that triggered this analysis
   */
  exampleAmount?: number | null;
  /**
   * Ollama's cleaned merchant / payee name (raw string)
   */
  suggestedPayee?: string | null;
  /**
   * Matched Payee record for Ollama's suggestion (auto-resolved; null if no payee record matched)
   */
  suggestedPayeeLink?: (string | null) | Payee;
  /**
   * Ollama's suggested expense category
   */
  suggestedExpenseCategory?: (string | null) | ExpenseCategory;
  /**
   * Ollama's suggested income category
   */
  suggestedIncomeCategory?: (string | null) | IncomeCategory;
  /**
   * Recurring items identified as possible matches based on amount and timing
   */
  suggestedRecurringItems?: (string | RecurringItem)[] | null;
  /**
   * Ollama's stated confidence level
   */
  ollamaConfidence?: ('high' | 'medium' | 'low') | null;
  /**
   * Set to Accepted to confirm values and auto-create a MatchRule for future syncs
   */
  status?: ('pending' | 'accepted' | 'rejected') | null;
  /**
   * Payee to assign (defaults to suggestedPayeeLink; create a new Payee record first if needed)
   */
  acceptedPayee?: (string | null) | Payee;
  /**
   * The expense category to use (defaults to suggested; override before accepting)
   */
  acceptedExpenseCategory?: (string | null) | ExpenseCategory;
  /**
   * The income category to use (defaults to suggested; override before accepting)
   */
  acceptedIncomeCategory?: (string | null) | IncomeCategory;
  /**
   * The recurring item to link (pick from suggestedRecurringItems or choose manually)
   */
  acceptedRecurringItem?: (string | null) | RecurringItem;
  /**
   * Raw Ollama response (for debugging)
   */
  ollamaRaw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'income-categories';
        value: string | IncomeCategory;
      } | null)
    | ({
        relationTo: 'expense-categories';
        value: string | ExpenseCategory;
      } | null)
    | ({
        relationTo: 'payees';
        value: string | Payee;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'recurring-items';
        value: string | RecurringItem;
      } | null)
    | ({
        relationTo: 'budgets';
        value: string | Budget;
      } | null)
    | ({
        relationTo: 'budget-items';
        value: string | BudgetItem;
      } | null)
    | ({
        relationTo: 'budget-schedules';
        value: string | BudgetSchedule;
      } | null)
    | ({
        relationTo: 'match-rules';
        value: string | MatchRule;
      } | null)
    | ({
        relationTo: 'app-settings';
        value: string | AppSetting;
      } | null)
    | ({
        relationTo: 'teller-insights';
        value: string | TellerInsight;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "income-categories_select".
 */
export interface IncomeCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories_select".
 */
export interface ExpenseCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payees_select".
 */
export interface PayeesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  name?: T;
  accountSource?: T;
  isDefault?: T;
  description?: T;
  accountType?: T;
  startingBalance?: T;
  currentBalance?: T;
  hasInterestRate?: T;
  interestRate?: T;
  scheduleType?: T;
  dayOfWeek?: T;
  anchorDate?: T;
  dayOfMonth?: T;
  month?: T;
  tellerAccountId?: T;
  tellerEnrollmentId?: T;
  tellerInstitutionName?: T;
  tellerAccessToken?: T;
  tellerLastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  date?: T;
  account?: T;
  type?: T;
  description?: T;
  displayTitle?: T;
  payee?: T;
  amount?: T;
  incomeDetails?:
    | T
    | {
        category?: T;
        payee?: T;
      };
  expenseDetails?:
    | T
    | {
        category?: T;
        payee?: T;
      };
  transferDetails?:
    | T
    | {
        toAccount?: T;
      };
  notes?: T;
  reconciled?: T;
  tellerTransactionId?: T;
  syncSource?: T;
  matchConfidence?: T;
  matchedRecurringItem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-items_select".
 */
export interface RecurringItemsSelect<T extends boolean = true> {
  category?: T;
  itemType?: T;
  name?: T;
  amount?: T;
  incomeCategory?: T;
  expenseCategory?: T;
  payee?: T;
  account?: T;
  fromAccount?: T;
  toAccount?: T;
  hasBalance?: T;
  balance?:
    | T
    | {
        currentBalance?: T;
        interestRate?: T;
      };
  scheduleType?: T;
  dayOfWeek?: T;
  anchorDate?: T;
  dayOfMonth?: T;
  month?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budgets_select".
 */
export interface BudgetsSelect<T extends boolean = true> {
  name?: T;
  account?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget-items_select".
 */
export interface BudgetItemsSelect<T extends boolean = true> {
  budget?: T;
  recurringItem?: T;
  dueDate?: T;
  isActualized?: T;
  transaction?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget-schedules_select".
 */
export interface BudgetSchedulesSelect<T extends boolean = true> {
  name?: T;
  account?: T;
  scheduleType?: T;
  dayOfWeek?: T;
  anchorDate?: T;
  dayOfMonth?: T;
  month?: T;
  budgetNamePattern?: T;
  isActive?: T;
  lookAhead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-rules_select".
 */
export interface MatchRulesSelect<T extends boolean = true> {
  name?: T;
  descriptionPattern?: T;
  transactionType?: T;
  amountMin?: T;
  amountMax?: T;
  recurringItem?: T;
  payee?: T;
  expenseCategory?: T;
  incomeCategory?: T;
  priority?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings_select".
 */
export interface AppSettingsSelect<T extends boolean = true> {
  wizardComplete?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teller-insights_select".
 */
export interface TellerInsightsSelect<T extends boolean = true> {
  descriptionKey?: T;
  exampleDescription?: T;
  transactionType?: T;
  exampleAmount?: T;
  suggestedPayee?: T;
  suggestedPayeeLink?: T;
  suggestedExpenseCategory?: T;
  suggestedIncomeCategory?: T;
  suggestedRecurringItems?: T;
  ollamaConfidence?: T;
  status?: T;
  acceptedPayee?: T;
  acceptedExpenseCategory?: T;
  acceptedIncomeCategory?: T;
  acceptedRecurringItem?: T;
  ollamaRaw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}